package com.datatalk.infra.opencode.process;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.GZIPOutputStream;

import static org.assertj.core.api.Assertions.assertThat;

class OpenCodeBinaryResolverDepsTest {

    @TempDir
    Path tempDir;

    @Test
    void ensureNodeModules_skipsWhenMarkerExists() {
        OpenCodeBinaryResolver resolver = new OpenCodeBinaryResolver();
        Path configDir = tempDir.resolve("opencode-config");
        Path nodeModules = configDir.resolve("node_modules");
        Path marker = configDir.resolve(".datatalk-deps-installed");

        // Simulate existing installation
        try {
            Files.createDirectories(nodeModules);
            Files.writeString(marker, "2026-04-20T00:00:00Z");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        // Should not throw and should not try to read classpath
        resolver.ensureNodeModulesWithConfigDir(configDir);

        // Marker still exists, no new files created
        assertThat(Files.exists(marker)).isTrue();
    }

    @Test
    void ensureNodeModules_extractsFromClasspath() {
        OpenCodeBinaryResolver resolver = new OpenCodeBinaryResolver();
        Path configDir = tempDir.resolve("opencode-config");

        // Classpath resource exists (generated by Maven build) — should extract
        resolver.ensureNodeModulesWithConfigDir(configDir);

        assertThat(Files.exists(configDir.resolve(".datatalk-deps-installed"))).isTrue();
        assertThat(Files.isDirectory(configDir.resolve("node_modules"))).isTrue();
    }

    @Test
    void extractDepsTarGz_extractsNodeModules() throws Exception {
        OpenCodeBinaryResolver resolver = new OpenCodeBinaryResolver();
        Path targetDir = tempDir.resolve("target");

        // Build a minimal tar.gz with node_modules/test-package/index.js
        byte[] tarGz = buildTestTarGz();

        resolver.extractDepsTarGz(new java.io.ByteArrayInputStream(tarGz), targetDir);

        assertThat(Files.exists(targetDir.resolve("node_modules"))).isTrue();
        assertThat(Files.exists(targetDir.resolve("node_modules/test-pkg/package.json"))).isTrue();
        assertThat(Files.readString(targetDir.resolve("node_modules/test-pkg/package.json")))
            .contains("test-pkg");
    }

    @Test
    void extractDepsTarGz_rejectsPathTraversal() throws Exception {
        OpenCodeBinaryResolver resolver = new OpenCodeBinaryResolver();
        Path targetDir = tempDir.resolve("target");

        // Build a tar.gz with a path traversal entry
        byte[] tarGz = buildPathTraversalTarGz();

        org.assertj.core.api.Assertions.assertThatThrownBy(() ->
            resolver.extractDepsTarGz(new java.io.ByteArrayInputStream(tarGz), targetDir)
        ).isInstanceOf(IOException.class)
         .hasMessageContaining("escapes target directory");
    }

    private byte[] buildTestTarGz() throws IOException {
        // Build a simple tar archive with: node_modules/test-pkg/package.json
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        var gzip = new GZIPOutputStream(baos);

        // Tar entry: node_modules/ (directory)
        byte[] dirHeader = buildTarHeader("node_modules/", 0, '5');
        gzip.write(dirHeader);

        // Tar entry: node_modules/test-pkg/ (directory)
        byte[] pkgDirHeader = buildTarHeader("node_modules/test-pkg/", 0, '5');
        gzip.write(pkgDirHeader);

        // Tar entry: node_modules/test-pkg/package.json (file)
        String content = "{\"name\":\"test-pkg\"}";
        byte[] contentBytes = content.getBytes();
        byte[] fileHeader = buildTarHeader("node_modules/test-pkg/package.json", contentBytes.length, '0');
        gzip.write(fileHeader);
        gzip.write(contentBytes);
        // Pad to 512-byte boundary
        int padding = (512 - (contentBytes.length % 512)) % 512;
        gzip.write(new byte[padding]);

        // End-of-archive marker (two 512-byte zero blocks)
        gzip.write(new byte[1024]);
        gzip.finish();
        return baos.toByteArray();
    }

    private byte[] buildPathTraversalTarGz() throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        var gzip = new GZIPOutputStream(baos);

        byte[] header = buildTarHeader("../../etc/passwd", 5, '0');
        gzip.write(header);
        gzip.write("hello".getBytes());
        gzip.write(new byte[512 - 5]);
        gzip.write(new byte[1024]);
        gzip.finish();
        return baos.toByteArray();
    }

    private byte[] buildTarHeader(String filename, long size, char typeFlag) {
        byte[] header = new byte[512];

        // Filename (0-99)
        byte[] nameBytes = filename.getBytes();
        System.arraycopy(nameBytes, 0, header, 0, Math.min(nameBytes.length, 99));

        // Mode (100-107): "0000644\0"
        byte[] mode = "0000644\0".getBytes();
        System.arraycopy(mode, 0, header, 100, mode.length);

        // UID (108-115)
        byte[] uid = "0000000\0".getBytes();
        System.arraycopy(uid, 0, header, 108, uid.length);

        // GID (116-123)
        System.arraycopy(uid, 0, header, 116, uid.length);

        // Size (124-135)
        String sizeStr = String.format("%011o\0", size);
        System.arraycopy(sizeStr.getBytes(), 0, header, 124, sizeStr.length());

        // Mtime (136-147)
        String mtime = String.format("%011o\0", System.currentTimeMillis() / 1000);
        System.arraycopy(mtime.getBytes(), 0, header, 136, mtime.length());

        // Checksum placeholder (148-155): spaces
        header[148] = ' ';
        header[149] = ' ';
        header[150] = ' ';
        header[151] = ' ';
        header[152] = ' ';
        header[153] = ' ';
        header[154] = ' ';
        header[155] = ' ';

        // Type flag (156)
        header[156] = (byte) typeFlag;

        // Compute checksum
        int checksum = 0;
        for (byte b : header) checksum += (b & 0xFF);
        String checksumStr = String.format("%06o\0 ", checksum);
        System.arraycopy(checksumStr.getBytes(), 0, header, 148, checksumStr.length());

        return header;
    }
}
