package com.datatalk.application.report;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.regex.Pattern;

/**
 * 报告 JSON → 自包含 HTML 派生器。
 *
 * <p>输出 HTML 通过 {@code <base href="${baseHref}">} 标签把所有相对资源（ledger.css、
 * 字体、ECharts JS）的解析根锚定到 {@code /api/reports/_assets/}（默认）—— 加载源
 * 不论是 HTTP（iframe）还是 Playwright（localhost HTTP）都能解析相对路径。
 *
 * <p>每个 chart block 容器加 {@code data-ledger-chart-id="<id>"} 属性，供
 * {@link ChartCaptureRenderer} 截图定位。
 *
 * <p>渲染完成后，所有 ECharts 实例的 {@code chart.on('finished')} 事件触发后会设置
 * {@code window.__LEDGER_READY__ = true}，{@link PdfRenderer} 通过 {@code page.waitForFunction}
 * 等待该信号才打印 PDF。
 */
@Service
public class ReportRenderer {

    private static final Logger log = LoggerFactory.getLogger(ReportRenderer.class);

    public static final String DEFAULT_ASSETS_BASE_HREF = "/api/reports/_assets/";

    /**
     * 黑名单：cover.author 命中此正则的值视为生成器自指水印，渲染时清空。
     * 例：{@code "DataTalk 自动生成"}、{@code "AI 生成"}、{@code "Generated by Foo"}。
     * 匹配整串、忽略大小写、允许零或一个分隔符（空白/中点/连字符）。
     */
    static final Pattern AUTHOR_WATERMARK_PATTERN = Pattern.compile(
            "^("
                    + "datatalk[\\s·\\-]?(自动生成|生成|auto[\\s\\-]?generated)"
                    + "|auto[\\s\\-]?generated"
                    + "|ai\\s?生成"
                    + "|自动生成"
                    + "|系统生成"
                    + "|generated\\s+by\\s+.*"
                    + ")$",
            Pattern.CASE_INSENSITIVE
    );

    /** 渲染层 sanitize：trim 后命中水印黑名单则返回 ""，记 warn 日志。 */
    public static String sanitizeAuthor(String author) {
        if (author == null) return "";
        String trimmed = author.trim();
        if (trimmed.isEmpty()) return "";
        if (AUTHOR_WATERMARK_PATTERN.matcher(trimmed).matches()) {
            log.warn("cover.author watermark stripped at render time: {}", trimmed);
            return "";
        }
        return trimmed;
    }

    /** chapter 预扫描结果，TOC 与 chapter 渲染共用同一份 1-based 索引。 */
    record ChapterInfo(int idx, String heading) {}

    private final ObjectMapper mapper;

    public ReportRenderer(ObjectMapper mapper) {
        this.mapper = mapper;
    }

    public String toHtml(JsonNode reportJson) {
        return toHtml(reportJson, DEFAULT_ASSETS_BASE_HREF);
    }

    public String toHtml(JsonNode reportJson, String assetsBaseHref) {
        JsonNode meta = reportJson.path("meta");
        String title = meta.path("title").asText("DataTalk Report");
        LedgerThemePalette palette = LedgerThemePalette.from(reportJson.path("theme"));

        StringBuilder html = new StringBuilder(64 * 1024);
        html.append("<!doctype html>\n");
        html.append("<html lang=\"zh\">\n<head>\n");
        html.append("<meta charset=\"utf-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        html.append("<title>").append(escapeHtml(title)).append("</title>\n");
        html.append("<base href=\"").append(escapeAttr(assetsBaseHref)).append("\">\n");
        html.append("<link rel=\"stylesheet\" href=\"styles/ledger.css\">\n");
        html.append(injectThemeVars(palette));
        html.append("<script src=\"scripts/echarts.min.js\"></script>\n");
        html.append("</head>\n<body>\n");
        html.append("<div class=\"ledger-report\">\n");

        // sections — predict chapter list so TOC and chapter renderers share the same 1-based index
        JsonNode sections = reportJson.path("sections");
        java.util.List<ChapterInfo> chapters = collectChapters(sections);
        if (sections.isArray()) {
            int chapterCursor = 0;
            for (JsonNode section : sections) {
                if ("chapter".equals(section.path("type").asText(""))) {
                    chapterCursor += 1;
                    renderChapter(section, chapterCursor, html);
                } else {
                    renderBlock(section, chapters, html);
                }
            }
        }
        // appendix
        JsonNode appendix = reportJson.path("appendix");
        if (appendix.isArray() && !appendix.isEmpty()) {
            html.append("<section class=\"ledger-appendix\">\n");
            for (JsonNode item : appendix) {
                renderBlock(item, chapters, html);
            }
            html.append("</section>\n");
        }

        html.append("</div>\n");

        // Chart init + LEDGER_READY signal
        html.append("<script>\n").append(renderChartBootstrapScript(reportJson, palette)).append("\n</script>\n");
        // BUG-0077: with <base href="…/_assets/"> a bare `<a href="#chap-N">` resolves to an
        // absolute URL against the base, triggering cross-document navigation on click.
        // Intercept hash links and use scrollIntoView so TOC anchors stay same-document.
        html.append("<script>\n").append(ANCHOR_INTERCEPTOR_SCRIPT).append("\n</script>\n");
        html.append("</body>\n</html>\n");
        return html.toString();
    }

    /**
     * Inline click delegate that prevents {@code <base href>} from turning {@code #chap-N}
     * links into cross-document navigations. Sits at end of body so it captures every TOC
     * link rendered above.
     */
    static final String ANCHOR_INTERCEPTOR_SCRIPT =
            "document.addEventListener('click', function(e){\n"
          + "  var a = e.target && e.target.closest && e.target.closest('a[href^=\"#\"]');\n"
          + "  if (!a) return;\n"
          + "  var id = a.getAttribute('href').slice(1);\n"
          + "  if (!id) return;\n"
          + "  var t = document.getElementById(id);\n"
          + "  if (!t) return;\n"
          + "  e.preventDefault();\n"
          + "  t.scrollIntoView({behavior:'smooth', block:'start'});\n"
          + "});";

    /**
     * 注入 {@code :root} CSS 变量，覆盖 ledger.css 的同名默认值。由 {@link LedgerThemePalette}
     * 解析 theme 调色板（缺省派生补齐），保证 primary/accent/surface/tint-1..4/语义色全部就位。
     */
    static String injectThemeVars(LedgerThemePalette palette) {
        return "<style>:root { " + palette.toCssVars() + " }</style>\n";
    }

    /**
     * 提取报告中所有 chart block 的 id 与 echartsOption，用于 bootstrap script。
     *
     * <p>在 {@code initOne} 中 setOption 前先注入由 theme 解析出的 8 色 PALETTE：
     * {@code inst.setOption({color:PALETTE}, false)} 先于 {@code inst.setOption(c.option)} ——
     * 两次 merge，报告自己在 echartsOption 里显式指定的 series 色仍胜出。
     */
    private String renderChartBootstrapScript(JsonNode reportJson, LedgerThemePalette palette) {
        StringBuilder s = new StringBuilder(4096);
        s.append("(function(){\n");
        s.append("  var PALETTE = ").append(paletteJsArray(palette)).append(";\n");
        s.append("  var charts = [\n");
        boolean first = true;
        for (JsonNode block : collectChartBlocks(reportJson)) {
            if (!first) s.append(",\n");
            first = false;
            String id = block.path("id").asText("");
            JsonNode option = block.path("echartsOption");
            String optionJson;
            try {
                optionJson = mapper.writeValueAsString(option);
            } catch (JsonProcessingException e) {
                optionJson = "{}";
            }
            s.append("    { id: ").append(jsString(id)).append(", option: ").append(optionJson).append(" }");
        }
        s.append("\n  ];\n");
        s.append("  var pending = charts.length;\n");
        s.append("  if (pending === 0) { window.__LEDGER_READY__ = true; return; }\n");
        s.append("  function markFinished(){ pending -= 1; if (pending <= 0) window.__LEDGER_READY__ = true; }\n");
        s.append("  function initOne(c){\n");
        s.append("    var el = document.querySelector('[data-ledger-chart-id=\"' + c.id + '\"]');\n");
        s.append("    if (!el || typeof echarts === 'undefined') { markFinished(); return; }\n");
        s.append("    try {\n");
        s.append("      var inst = echarts.init(el);\n");
        s.append("      inst.on('finished', markFinished);\n");
        s.append("      inst.setOption({ color: PALETTE }, false);\n");
        s.append("      inst.setOption(c.option);\n");
        s.append("    } catch (e) {\n");
        s.append("      console.error('ledger chart init failed', c.id, e);\n");
        s.append("      markFinished();\n");
        s.append("    }\n");
        s.append("  }\n");
        s.append("  if (document.readyState === 'complete' || document.readyState === 'interactive') {\n");
        s.append("    charts.forEach(initOne);\n");
        s.append("  } else {\n");
        s.append("    document.addEventListener('DOMContentLoaded', function(){ charts.forEach(initOne); });\n");
        s.append("  }\n");
        s.append("})();\n");
        return s.toString();
    }

    private static java.util.List<JsonNode> collectChartBlocks(JsonNode root) {
        java.util.List<JsonNode> result = new java.util.ArrayList<>();
        walkBlocks(root.path("sections"), result);
        walkBlocks(root.path("appendix"), result);
        return result;
    }

    private static void walkBlocks(JsonNode arr, java.util.List<JsonNode> out) {
        if (!arr.isArray()) return;
        for (JsonNode block : arr) {
            String type = block.path("type").asText("");
            if ("chart".equals(type)) {
                out.add(block);
            } else if ("chapter".equals(type)) {
                walkBlocks(block.path("blocks"), out);
            }
        }
    }

    private void renderBlock(JsonNode block, java.util.List<ChapterInfo> chapters, StringBuilder out) {
        String type = block.path("type").asText("");
        switch (type) {
            case "cover" -> renderCover(block, out);
            case "executive-summary" -> renderExecutiveSummary(block, out);
            case "toc" -> renderToc(chapters, out);
            // chapter 由 toHtml 直接调用 renderChapter(block, idx, out)，不走 renderBlock
            case "chapter" -> renderChapter(block, 0, out);
            case "kpi-strip" -> renderKpiStrip(block, out);
            case "narrative" -> renderNarrative(block, out);
            case "chart" -> renderChart(block, out);
            case "table" -> renderTable(block, out);
            case "risk-list" -> renderRiskList(block, out);
            case "timeline" -> renderTimeline(block, out);
            case "appendix" -> renderAppendix(block, out);
            case "callout" -> renderCallout(block, out);
            case "stat-highlight" -> renderStatHighlight(block, out);
            case "comparison" -> renderComparison(block, out);
            case "quote" -> renderQuote(block, out);
            case "divider" -> renderDivider(block, out);
            default -> out.append("<!-- unknown block ").append(escapeHtml(type)).append(" -->\n");
        }
    }

    static java.util.List<ChapterInfo> collectChapters(JsonNode sections) {
        java.util.List<ChapterInfo> chapters = new java.util.ArrayList<>();
        if (!sections.isArray()) return chapters;
        int idx = 0;
        for (JsonNode section : sections) {
            if ("chapter".equals(section.path("type").asText(""))) {
                idx += 1;
                chapters.add(new ChapterInfo(idx, section.path("heading").asText("")));
            }
        }
        return chapters;
    }

    private void renderCover(JsonNode b, StringBuilder out) {
        out.append("<section class=\"ledger-cover\">\n");
        out.append("  <div class=\"ledger-cover__accent-bar\" style=\"background: var(--ledger-accent)\"></div>\n");
        out.append("  <h1 class=\"ledger-cover__title\">").append(escapeHtml(b.path("title").asText(""))).append("</h1>\n");
        String subtitle = b.path("subtitle").asText("");
        if (!subtitle.isBlank()) {
            out.append("  <h3 class=\"ledger-cover__subtitle\">").append(escapeHtml(subtitle)).append("</h3>\n");
        }
        StringBuilder meta = new StringBuilder();
        String author = sanitizeAuthor(b.path("author").asText(""));
        if (!author.isBlank()) meta.append(escapeHtml(author));
        if (!b.path("date").asText("").isBlank()) {
            if (meta.length() > 0) meta.append(" · ");
            meta.append(escapeHtml(b.path("date").asText("")));
        }
        if (meta.length() > 0) {
            out.append("  <p class=\"ledger-cover__meta\">").append(meta).append("</p>\n");
        }
        out.append("</section>\n");
    }

    private void renderExecutiveSummary(JsonNode b, StringBuilder out) {
        out.append("<section class=\"ledger-executive-summary\">\n");
        out.append("  <h2>摘要</h2>\n");
        JsonNode bullets = b.path("bullets");
        if (bullets.isArray()) {
            out.append("  <ul>\n");
            for (JsonNode bul : bullets) {
                out.append("    <li>").append(escapeHtml(bul.asText(""))).append("</li>\n");
            }
            out.append("  </ul>\n");
        }
        out.append("</section>\n");
    }

    private void renderToc(java.util.List<ChapterInfo> chapters, StringBuilder out) {
        out.append("<section class=\"ledger-toc\"><h2>目录</h2><ol>");
        for (ChapterInfo c : chapters) {
            out.append("<li><a href=\"#chap-").append(c.idx()).append("\">")
                    .append(escapeHtml(c.heading()))
                    .append("</a></li>");
        }
        out.append("</ol></section>\n");
    }

    private void renderChapter(JsonNode b, int idx, StringBuilder out) {
        out.append("<section class=\"ledger-chapter\" id=\"chap-").append(idx).append("\">\n");
        out.append("  <h2 class=\"ledger-chapter__heading\">").append(escapeHtml(b.path("heading").asText(""))).append("</h2>\n");
        JsonNode blocks = b.path("blocks");
        if (blocks.isArray()) {
            // 嵌套 blocks 不可能再含 chapter，所以 chapters 列表对嵌套渲染无意义；传 null 占位
            for (JsonNode child : blocks) renderBlock(child, java.util.List.of(), out);
        }
        out.append("</section>\n");
    }

    private void renderKpiStrip(JsonNode b, StringBuilder out) {
        out.append("<div class=\"ledger-kpi-strip\">\n");
        JsonNode items = b.path("items");
        if (items.isArray()) {
            for (JsonNode it : items) {
                out.append("  <div class=\"ledger-kpi-card\">\n");
                out.append("    <div class=\"ledger-kpi-card__label\">").append(escapeHtml(it.path("label").asText(""))).append("</div>\n");
                out.append("    <div class=\"ledger-kpi-card__value\">").append(escapeHtml(it.path("value").asText(""))).append("</div>\n");
                String delta = it.path("delta").asText("");
                if (!delta.isBlank()) {
                    boolean up = delta.contains("+") || delta.startsWith("↑");
                    String cls = up ? "ledger-kpi-card__delta ledger-kpi-card__delta--up" : "ledger-kpi-card__delta ledger-kpi-card__delta--down";
                    String arrow = up ? "↑" : "↓";
                    out.append("    <div class=\"").append(cls).append("\">").append(arrow).append(" ")
                            .append(escapeHtml(delta.replace("+", "").replace("-", ""))).append("</div>\n");
                }
                out.append("  </div>\n");
            }
        }
        out.append("</div>\n");
        renderSource(b, out);
    }

    private void renderNarrative(JsonNode b, StringBuilder out) {
        out.append("<div class=\"ledger-narrative\">");
        String md = b.path("markdown").asText("");
        out.append(simpleMarkdownToHtml(md));
        out.append("</div>\n");
    }

    private void renderChart(JsonNode b, StringBuilder out) {
        String id = b.path("id").asText("");
        out.append("<figure class=\"ledger-chart\">\n");
        out.append("  <div data-ledger-chart-id=\"").append(escapeAttr(id)).append("\" style=\"height:360px\"></div>\n");
        String caption = b.path("caption").asText("");
        if (!caption.isBlank()) {
            out.append("  <figcaption>").append(escapeHtml(caption)).append("</figcaption>\n");
        }
        out.append("</figure>\n");
        renderSource(b, out);
    }

    private void renderTable(JsonNode b, StringBuilder out) {
        JsonNode columns = b.path("columns");
        JsonNode rows = b.path("rows");
        int colCount = columns.isArray() ? columns.size() : 0;

        // 列级 cellFormats（可选）：长度对齐 columns；未声明的列退化为纯文本
        java.util.List<String> formats = new java.util.ArrayList<>();
        JsonNode cellFormats = b.path("cellFormats");
        if (cellFormats.isArray()) {
            for (JsonNode f : cellFormats) formats.add(f.asText("text"));
        }
        // bar/heat 需列内数值区间做归一化，先做一次预扫描
        double[] colMin = new double[colCount];
        double[] colMax = new double[colCount];
        boolean[] colHasNum = new boolean[colCount];
        java.util.Arrays.fill(colMin, Double.POSITIVE_INFINITY);
        java.util.Arrays.fill(colMax, Double.NEGATIVE_INFINITY);
        if (rows.isArray() && !formats.isEmpty()) {
            for (JsonNode row : rows) {
                if (!row.isArray()) continue;
                for (int c = 0; c < colCount && c < row.size(); c++) {
                    String fmt = c < formats.size() ? formats.get(c) : "text";
                    if (!"bar".equals(fmt) && !"heat".equals(fmt)) continue;
                    Double v = parseNumeric(row.get(c).asText(""));
                    if (v != null) {
                        colHasNum[c] = true;
                        colMin[c] = Math.min(colMin[c], v);
                        colMax[c] = Math.max(colMax[c], v);
                    }
                }
            }
        }

        boolean paged = rows.isArray() && rows.size() > 30;
        out.append("<figure class=\"ledger-table").append(paged ? " ledger-table--paged" : "").append("\">\n");
        String caption = b.path("caption").asText("");
        if (!caption.isBlank()) {
            out.append("  <figcaption>").append(escapeHtml(caption)).append("</figcaption>\n");
        }
        out.append("  <table>\n");
        if (columns.isArray()) {
            out.append("    <thead><tr>");
            for (JsonNode c : columns) {
                out.append("<th>").append(escapeHtml(c.asText(""))).append("</th>");
            }
            out.append("</tr></thead>\n");
        }
        if (rows.isArray()) {
            out.append("    <tbody>\n");
            for (JsonNode row : rows) {
                out.append("      <tr>");
                if (row.isArray()) {
                    for (int c = 0; c < row.size(); c++) {
                        String raw = row.get(c).asText("");
                        String fmt = (c < formats.size()) ? formats.get(c) : "text";
                        renderCell(raw, fmt, c, colMin, colMax, colHasNum, colCount, out);
                    }
                }
                out.append("</tr>\n");
            }
            out.append("    </tbody>\n");
        }
        out.append("  </table>\n");
        String appendixCsvRef = b.path("appendixCsvRef").asText("");
        if (!appendixCsvRef.isBlank()) {
            out.append("  <p class=\"ledger-table__appendix-note\">完整数据见附录 CSV：<a href=\"/api/file-artifacts/")
                    .append(escapeAttr(appendixCsvRef)).append("/download\">下载</a></p>\n");
        }
        out.append("</figure>\n");
        renderSource(b, out);
    }

    /** 单元格渲染：按列级 format 修饰。数值解析失败一律安全回退纯文本，不抛异常。 */
    private void renderCell(String raw, String fmt, int col,
                            double[] colMin, double[] colMax, boolean[] colHasNum,
                            int colCount, StringBuilder out) {
        boolean inRange = col >= 0 && col < colCount;
        switch (fmt) {
            case "bar" -> {
                Double v = parseNumeric(raw);
                if (v == null || !inRange || !colHasNum[col]) {
                    out.append("<td>").append(escapeHtml(raw)).append("</td>");
                    return;
                }
                double pct = barWidthPct(v, colMin[col], colMax[col]);
                out.append("<td class=\"ledger-cell--bar\">")
                        .append("<span class=\"ledger-cell-bar\"><span class=\"ledger-cell-bar__fill\" style=\"width:")
                        .append(formatPct(pct)).append("%\"></span></span>")
                        .append("<span class=\"ledger-cell-bar__label\">").append(escapeHtml(raw)).append("</span>")
                        .append("</td>");
            }
            case "delta" -> {
                Double v = parseNumeric(raw);
                if (v == null) {
                    out.append("<td>").append(escapeHtml(raw)).append("</td>");
                    return;
                }
                boolean up = v >= 0 && !raw.trim().startsWith("-");
                String cls = up ? "ledger-cell--delta ledger-cell--delta-up"
                        : "ledger-cell--delta ledger-cell--delta-down";
                String arrow = up ? "↑" : "↓";
                out.append("<td class=\"").append(cls).append("\">").append(arrow).append(" ")
                        .append(escapeHtml(raw)).append("</td>");
            }
            case "heat" -> {
                Double v = parseNumeric(raw);
                if (v == null || !inRange || !colHasNum[col]) {
                    out.append("<td>").append(escapeHtml(raw)).append("</td>");
                    return;
                }
                int level = heatLevel(v, colMin[col], colMax[col]);
                out.append("<td class=\"ledger-cell--heat ledger-cell--heat-").append(level).append("\">")
                        .append(escapeHtml(raw)).append("</td>");
            }
            default -> out.append("<td>").append(escapeHtml(raw)).append("</td>");
        }
    }

    private static double barWidthPct(double v, double min, double max) {
        if (max <= min) return v > 0 ? 100.0 : 0.0;
        double base = Math.min(min, 0.0);
        double pct = (v - base) / (max - base) * 100.0;
        return Math.max(0.0, Math.min(100.0, pct));
    }

    /** 数值映射到 1-4 档热力等级（4 最深）。 */
    private static int heatLevel(double v, double min, double max) {
        if (max <= min) return 1;
        double norm = (v - min) / (max - min);
        int level = (int) Math.floor(norm * 4) + 1;
        return Math.max(1, Math.min(4, level));
    }

    private static String formatPct(double pct) {
        return String.format(java.util.Locale.ROOT, "%.1f", pct);
    }

    private static final Pattern NUMERIC_TOKEN =
            Pattern.compile("-?\\d[\\d,]*\\.?\\d*");

    /** 从文本中抽取首个数值（容忍千分位逗号、货币/百分号等前后缀）。无数值返回 null。 */
    static Double parseNumeric(String s) {
        if (s == null || s.isBlank()) return null;
        java.util.regex.Matcher m = NUMERIC_TOKEN.matcher(s.trim());
        if (!m.find()) return null;
        String token = m.group().replace(",", "");
        if (token.isEmpty() || "-".equals(token) || ".".equals(token)) return null;
        try {
            return Double.parseDouble(token);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private void renderRiskList(JsonNode b, StringBuilder out) {
        out.append("<ul class=\"ledger-risk-list\">\n");
        JsonNode items = b.path("items");
        if (items.isArray()) {
            for (JsonNode it : items) {
                String severity = it.path("severity").asText("low");
                String emoji = switch (severity) {
                    case "critical" -> "🔴";
                    case "high" -> "🟠";
                    case "medium" -> "🟡";
                    default -> "🟢";
                };
                out.append("  <li class=\"ledger-risk-item ledger-risk-item--").append(escapeAttr(severity)).append("\">\n");
                out.append("    <span class=\"ledger-risk-item__severity\">").append(emoji).append("</span>\n");
                out.append("    <span class=\"ledger-risk-item__desc\">").append(escapeHtml(it.path("description").asText(""))).append("</span>\n");
                StringBuilder meta = new StringBuilder();
                if (!it.path("owner").asText("").isBlank()) meta.append(escapeHtml(it.path("owner").asText("")));
                if (!it.path("dueDate").asText("").isBlank()) {
                    if (meta.length() > 0) meta.append(" · ");
                    meta.append(escapeHtml(it.path("dueDate").asText("")));
                }
                if (meta.length() > 0) {
                    out.append("    <span class=\"ledger-risk-item__meta\">").append(meta).append("</span>\n");
                }
                out.append("  </li>\n");
            }
        }
        out.append("</ul>\n");
    }

    private void renderTimeline(JsonNode b, StringBuilder out) {
        out.append("<ol class=\"ledger-timeline\">\n");
        JsonNode events = b.path("events");
        if (events.isArray()) {
            for (JsonNode ev : events) {
                out.append("  <li class=\"ledger-timeline__event\">\n");
                out.append("    <time>").append(escapeHtml(ev.path("at").asText(""))).append("</time>\n");
                out.append("    <strong>").append(escapeHtml(ev.path("title").asText(""))).append("</strong>\n");
                out.append("    <p>").append(escapeHtml(ev.path("description").asText(""))).append("</p>\n");
                out.append("  </li>\n");
            }
        }
        out.append("</ol>\n");
    }

    private void renderAppendix(JsonNode b, StringBuilder out) {
        String subType = b.path("subType").asText("");
        String title = b.path("title").asText("");
        out.append("<div class=\"ledger-appendix-block\">\n");
        if (!title.isBlank()) {
            out.append("  <h3>").append(escapeHtml(title)).append("</h3>\n");
        }
        JsonNode items = b.path("items");
        if (items.isArray()) {
            switch (subType) {
                case "sql-listing" -> {
                    for (JsonNode it : items) {
                        out.append("  <div class=\"ledger-appendix__sql-purpose\">").append(escapeHtml(it.path("purpose").asText(""))).append("</div>\n");
                        out.append("  <pre class=\"ledger-appendix__sql\">").append(escapeHtml(it.path("sql").asText(""))).append("</pre>\n");
                    }
                }
                case "glossary" -> {
                    out.append("  <dl>\n");
                    for (JsonNode it : items) {
                        out.append("    <dt>").append(escapeHtml(it.path("term").asText(""))).append("</dt>\n");
                        out.append("    <dd>").append(escapeHtml(it.path("definition").asText(""))).append("</dd>\n");
                    }
                    out.append("  </dl>\n");
                }
                case "csv-link" -> {
                    out.append("  <ul>\n");
                    for (JsonNode it : items) {
                        out.append("    <li><a href=\"/api/file-artifacts/")
                                .append(escapeAttr(it.path("fileArtifactId").asText("")))
                                .append("/download\">")
                                .append(escapeHtml(it.path("caption").asText(""))).append("</a></li>\n");
                    }
                    out.append("  </ul>\n");
                }
                default -> out.append("  <!-- unknown appendix subType: ").append(escapeHtml(subType)).append(" -->\n");
            }
        }
        out.append("</div>\n");
    }

    /** key-insight 高亮块。色彩由 variant 经 CSS class 映射到角色色，渲染层不写裸 hex。 */
    private void renderCallout(JsonNode b, StringBuilder out) {
        String variant = b.path("variant").asText("note");
        if (!java.util.Set.of("insight", "warning", "note", "success").contains(variant)) {
            variant = "note";
        }
        String icon = switch (variant) {
            case "insight" -> "💡";
            case "warning" -> "⚠️";
            case "success" -> "✅";
            default -> "📝";
        };
        out.append("<aside class=\"ledger-callout ledger-callout--").append(variant).append("\">\n");
        out.append("  <div class=\"ledger-callout__icon\" aria-hidden=\"true\">").append(icon).append("</div>\n");
        out.append("  <div class=\"ledger-callout__body\">\n");
        String title = b.path("title").asText("");
        if (!title.isBlank()) {
            out.append("    <div class=\"ledger-callout__title\">").append(escapeHtml(title)).append("</div>\n");
        }
        out.append("    <div class=\"ledger-callout__content\">").append(simpleMarkdownToHtml(b.path("markdown").asText(""))).append("</div>\n");
        out.append("  </div>\n");
        out.append("</aside>\n");
        renderSource(b, out);
    }

    /** hero 关键指标。value 用最大字号 + primary 色（由 CSS 定义）。 */
    private void renderStatHighlight(JsonNode b, StringBuilder out) {
        out.append("<div class=\"ledger-stat-highlight\">\n");
        out.append("  <div class=\"ledger-stat-highlight__value ledger-num\">").append(escapeHtml(b.path("value").asText(""))).append("</div>\n");
        String label = b.path("label").asText("");
        if (!label.isBlank()) {
            out.append("  <div class=\"ledger-stat-highlight__label\">").append(escapeHtml(label)).append("</div>\n");
        }
        String context = b.path("context").asText("");
        if (!context.isBlank()) {
            out.append("  <div class=\"ledger-stat-highlight__context\">").append(escapeHtml(context)).append("</div>\n");
        }
        String delta = b.path("delta").asText("");
        if (!delta.isBlank()) {
            boolean up = delta.contains("+") || delta.startsWith("↑");
            String cls = up ? "ledger-stat-highlight__delta ledger-stat-highlight__delta--up"
                    : "ledger-stat-highlight__delta ledger-stat-highlight__delta--down";
            String arrow = up ? "↑" : "↓";
            out.append("  <div class=\"").append(cls).append("\">").append(arrow).append(" ")
                    .append(escapeHtml(delta.replace("+", "").replace("-", ""))).append("</div>\n");
        }
        out.append("</div>\n");
        renderSource(b, out);
    }

    /** 并列对比卡（2-4 等宽卡片）。 */
    private void renderComparison(JsonNode b, StringBuilder out) {
        out.append("<div class=\"ledger-comparison\">\n");
        JsonNode items = b.path("items");
        if (items.isArray()) {
            for (JsonNode it : items) {
                out.append("  <div class=\"ledger-comparison__item\">\n");
                out.append("    <div class=\"ledger-comparison__label\">").append(escapeHtml(it.path("label").asText(""))).append("</div>\n");
                out.append("    <div class=\"ledger-comparison__value ledger-num\">").append(escapeHtml(it.path("value").asText(""))).append("</div>\n");
                String caption = it.path("caption").asText("");
                if (!caption.isBlank()) {
                    out.append("    <div class=\"ledger-comparison__caption\">").append(escapeHtml(caption)).append("</div>\n");
                }
                out.append("  </div>\n");
            }
        }
        out.append("</div>\n");
        renderSource(b, out);
    }

    /** pull-quote。 */
    private void renderQuote(JsonNode b, StringBuilder out) {
        out.append("<blockquote class=\"ledger-quote\">\n");
        out.append("  <p class=\"ledger-quote__text\">").append(escapeHtml(b.path("text").asText(""))).append("</p>\n");
        String attribution = b.path("attribution").asText("");
        if (!attribution.isBlank()) {
            out.append("  <cite class=\"ledger-quote__attribution\">").append(escapeHtml(attribution)).append("</cite>\n");
        }
        out.append("</blockquote>\n");
    }

    /** 章节视觉分隔（细 hairline + 可选居中标签）。 */
    private void renderDivider(JsonNode b, StringBuilder out) {
        String label = b.path("label").asText("");
        if (label.isBlank()) {
            out.append("<hr class=\"ledger-divider\">\n");
        } else {
            out.append("<div class=\"ledger-divider ledger-divider--labeled\">")
                    .append("<span class=\"ledger-divider__label\">").append(escapeHtml(label)).append("</span></div>\n");
        }
    }

    private void renderSource(JsonNode b, StringBuilder out) {
        String source = b.path("source").asText("");
        if (!source.isBlank()) {
            out.append("<div class=\"ledger-block-source\">").append(escapeHtml(source)).append("</div>\n");
        }
    }

    /** 最小 markdown 渲染：段落分隔 + **bold** + *italic*。复杂语法在 v0 不支持。 */
    static String simpleMarkdownToHtml(String md) {
        if (md == null || md.isEmpty()) return "";
        String escaped = escapeHtml(md);
        // **bold**
        escaped = escaped.replaceAll("\\*\\*(.+?)\\*\\*", "<strong>$1</strong>");
        // *italic* (避开已替换的 strong)
        escaped = escaped.replaceAll("(?<!\\w)\\*([^*]+)\\*(?!\\w)", "<em>$1</em>");
        // paragraphs
        String[] paragraphs = escaped.split("\\n\\s*\\n");
        StringBuilder sb = new StringBuilder();
        for (String p : paragraphs) {
            if (p.isBlank()) continue;
            sb.append("<p>").append(p.replace("\n", "<br>")).append("</p>");
        }
        return sb.toString();
    }

    static String escapeHtml(String s) {
        if (s == null) return "";
        return s
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }

    static String escapeAttr(String s) {
        if (s == null) return "";
        return s
                .replace("&", "&amp;")
                .replace("\"", "&quot;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }

    private static String jsString(String s) {
        if (s == null) return "\"\"";
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
    }

    /** 把调色板 8 色解析为 JS 字面字符串数组（已是合法 hex，无需转义）。 */
    private static String paletteJsArray(LedgerThemePalette palette) {
        StringBuilder sb = new StringBuilder("[");
        String[] colors = palette.echartsPalette();
        for (int i = 0; i < colors.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(jsString(colors[i]));
        }
        return sb.append("]").toString();
    }
}
