package com.datatalk.infra.er;

import com.datatalk.application.er.ErDdlGenerator;
import com.datatalk.domain.er.ErDesignerColumn;
import com.datatalk.domain.er.ErDesignerIndex;
import com.datatalk.domain.er.ErDesignerRelation;
import com.datatalk.domain.er.ErDesignerTable;
import com.datatalk.domain.er.ErSchemaDiff;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class PostgresDdlGeneratorTest {

    private final PostgresDdlGenerator generator = new PostgresDdlGenerator();

    @Test
    void createTableUsesPostgresQuotingAndIdentity() {
        var table = new ErDesignerTable(
            "t1", "users", null,
            List.of(
                new ErDesignerColumn("c1", "id", "BIGINT", false, true, true, null, null),
                new ErDesignerColumn("c2", "email", "VARCHAR(255)", false, false, false, null, "ignored day one")
            ),
            List.of(), List.of()
        );

        var sql = generatedSql(generator.generate(new ErSchemaDiff.TableAdded(table)));

        assertThat(sql).startsWith("CREATE TABLE \"users\" (");
        assertThat(sql).contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        assertThat(sql).contains("\"email\" VARCHAR(255) NOT NULL");
        assertThat(sql).doesNotContain("COMMENT");
    }

    @Test
    void addColumnEmitsAlterTableAddColumn() {
        var column = new ErDesignerColumn("c", "discount", "NUMERIC(10,2)", true, false, false, null, null);

        assertThat(generatedSql(generator.generate(new ErSchemaDiff.ColumnAdded("orders", column))))
            .isEqualTo("ALTER TABLE \"orders\" ADD COLUMN \"discount\" NUMERIC(10,2)");
    }

    @Test
    void addForeignKeyEmitsAlterTableAddConstraint() {
        var relation = new ErDesignerRelation("r1", "orders", "user_id", "users", "id", "many_to_one", "database_fk");

        var sql = generatedSql(generator.generate(new ErSchemaDiff.ConstraintAdded(relation)));

        assertThat(sql).contains("ALTER TABLE \"orders\" ADD CONSTRAINT \"fk_orders_user_id\"");
        assertThat(sql).contains("FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\")");
    }

    @Test
    void createIndexEmitsCreateIndex() {
        var index = new ErDesignerIndex("idx_orders_created_at", List.of("created_at"));

        assertThat(generatedSql(generator.generate(new ErSchemaDiff.IndexAdded("orders", index))))
            .isEqualTo("CREATE INDEX \"idx_orders_created_at\" ON \"orders\" (\"created_at\")");
    }

    @Test
    void destructiveChangesAreSkipped() {
        var result = generator.generate(new ErSchemaDiff.TableDropped("orders"));

        assertThat(result).isInstanceOf(ErDdlGenerator.GenerateResult.Skipped.class);
        assertThat(((ErDdlGenerator.GenerateResult.Skipped) result).skipped().reason()).isEqualTo("day1_unsupported");
    }

    private static String generatedSql(ErDdlGenerator.GenerateResult result) {
        assertThat(result).isInstanceOf(ErDdlGenerator.GenerateResult.Generated.class);
        return ((ErDdlGenerator.GenerateResult.Generated) result).statement().sql();
    }
}
