package com.datatalk.application.er;

import com.datatalk.domain.er.Dialect;

import java.util.Map;

public final class DialectTypeRegistry {

    private DialectTypeRegistry() {}

    public enum AbstractType {
        BIGINT, INT, SMALLINT, DECIMAL, VARCHAR, TEXT, BOOLEAN, DATE, TIMESTAMP, JSON, BLOB
    }

    public static String render(Dialect dialect, AbstractType type, Map<String, Object> params) {
        return switch (type) {
            case BIGINT -> switch (dialect) {
                case SQLITE -> "INTEGER";
                default -> "BIGINT";
            };
            case INT -> switch (dialect) {
                case POSTGRESQL, SQLITE -> "INTEGER";
                case MYSQL, H2, MARIADB -> "INT";
                case ORACLE, SQLSERVER -> "INT";
            };
            case SMALLINT -> switch (dialect) {
                case SQLITE -> "INTEGER";
                default -> "SMALLINT";
            };
            case DECIMAL -> decimal(dialect, params);
            case VARCHAR -> varchar(dialect, params);
            case TEXT -> (dialect == Dialect.H2 || dialect == Dialect.ORACLE) ? "CLOB" : "TEXT";
            case BOOLEAN -> switch (dialect) {
                case MYSQL, MARIADB -> "TINYINT(1)";
                case SQLITE -> "INTEGER";
                case POSTGRESQL, H2 -> "BOOLEAN";
                case ORACLE -> "NUMBER(1)";
                case SQLSERVER -> "BIT";
            };
            case DATE -> switch (dialect) {
                case SQLITE -> "TEXT";
                default -> "DATE";
            };
            case TIMESTAMP -> switch (dialect) {
                case SQLITE -> "TEXT";
                default -> "TIMESTAMP";
            };
            case JSON -> switch (dialect) {
                case POSTGRESQL -> "JSONB";
                case SQLITE -> "TEXT";
                case MYSQL, H2, MARIADB -> "JSON";
                case ORACLE -> "CLOB";
                case SQLSERVER -> "NVARCHAR(MAX)";
            };
            case BLOB -> switch (dialect) {
                case POSTGRESQL -> "BYTEA";
                case ORACLE -> "BLOB";
                case SQLSERVER -> "VARBINARY(MAX)";
                default -> "BLOB";
            };
        };
    }

    public static String quote(Dialect dialect, String identifier) {
        String ident = identifier == null ? "" : identifier;
        return switch (dialect) {
            case MYSQL, MARIADB -> "`" + ident.replace("`", "``") + "`";
            case SQLSERVER -> "[" + ident.replace("]", "]]") + "]";
            case POSTGRESQL, H2, SQLITE, ORACLE -> "\"" + ident.replace("\"", "\"\"") + "\"";
        };
    }

    public static String autoIncrementPk(Dialect dialect, String columnName) {
        String quoted = quote(dialect, columnName);
        return switch (dialect) {
            case MYSQL, MARIADB -> quoted + " BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> quoted + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case H2 -> quoted + " BIGINT AUTO_INCREMENT PRIMARY KEY";
            case SQLITE -> quoted + " INTEGER PRIMARY KEY AUTOINCREMENT";
            case ORACLE -> throw new UnsupportedOperationException("ER DDL not supported for Oracle");
            case SQLSERVER -> throw new UnsupportedOperationException("ER DDL not supported for SQL Server");
        };
    }

    private static String decimal(Dialect dialect, Map<String, Object> params) {
        int precision = intParam(params, "precision", 10);
        int scale = intParam(params, "scale", 2);
        String name = dialect == Dialect.POSTGRESQL || dialect == Dialect.SQLITE ? "NUMERIC" : "DECIMAL";
        return name + "(" + precision + "," + scale + ")";
    }

    private static String varchar(Dialect dialect, Map<String, Object> params) {
        if (dialect == Dialect.SQLITE) return "TEXT";
        return "VARCHAR(" + intParam(params, "len", 255) + ")";
    }

    private static int intParam(Map<String, Object> params, String key, int defaultValue) {
        Object value = params == null ? null : params.get(key);
        if (value instanceof Number number) return number.intValue();
        if (value instanceof String string && !string.isBlank()) return Integer.parseInt(string);
        return defaultValue;
    }
}
