package com.datatalk.application.er;

import com.datatalk.domain.er.Dialect;

import java.util.Map;

public final class DialectTypeRegistry {

    private DialectTypeRegistry() {}

    public enum AbstractType {
        BIGINT, INT, SMALLINT, DECIMAL, VARCHAR, TEXT, BOOLEAN, DATE, TIMESTAMP, JSON, BLOB
    }

    public static String render(Dialect dialect, AbstractType type, Map<String, Object> params) {
        return switch (type) {
            case BIGINT -> dialect == Dialect.SQLITE ? "INTEGER" : "BIGINT";
            case INT -> switch (dialect) {
                case POSTGRESQL, SQLITE -> "INTEGER";
                case MYSQL, H2 -> "INT";
            };
            case SMALLINT -> dialect == Dialect.SQLITE ? "INTEGER" : "SMALLINT";
            case DECIMAL -> decimal(dialect, params);
            case VARCHAR -> varchar(dialect, params);
            case TEXT -> dialect == Dialect.H2 ? "CLOB" : "TEXT";
            case BOOLEAN -> switch (dialect) {
                case MYSQL -> "TINYINT(1)";
                case SQLITE -> "INTEGER";
                case POSTGRESQL, H2 -> "BOOLEAN";
            };
            case DATE -> dialect == Dialect.SQLITE ? "TEXT" : "DATE";
            case TIMESTAMP -> dialect == Dialect.SQLITE ? "TEXT" : "TIMESTAMP";
            case JSON -> switch (dialect) {
                case POSTGRESQL -> "JSONB";
                case SQLITE -> "TEXT";
                case MYSQL, H2 -> "JSON";
            };
            case BLOB -> dialect == Dialect.POSTGRESQL ? "BYTEA" : "BLOB";
        };
    }

    public static String quote(Dialect dialect, String identifier) {
        String ident = identifier == null ? "" : identifier;
        if (dialect == Dialect.MYSQL) {
            return "`" + ident.replace("`", "``") + "`";
        }
        return "\"" + ident.replace("\"", "\"\"") + "\"";
    }

    public static String autoIncrementPk(Dialect dialect, String columnName) {
        String quoted = quote(dialect, columnName);
        return switch (dialect) {
            case MYSQL -> quoted + " BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> quoted + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case H2 -> quoted + " BIGINT AUTO_INCREMENT PRIMARY KEY";
            case SQLITE -> quoted + " INTEGER PRIMARY KEY AUTOINCREMENT";
        };
    }

    private static String decimal(Dialect dialect, Map<String, Object> params) {
        int precision = intParam(params, "precision", 10);
        int scale = intParam(params, "scale", 2);
        String name = dialect == Dialect.POSTGRESQL || dialect == Dialect.SQLITE ? "NUMERIC" : "DECIMAL";
        return name + "(" + precision + "," + scale + ")";
    }

    private static String varchar(Dialect dialect, Map<String, Object> params) {
        if (dialect == Dialect.SQLITE) return "TEXT";
        return "VARCHAR(" + intParam(params, "len", 255) + ")";
    }

    private static int intParam(Map<String, Object> params, String key, int defaultValue) {
        Object value = params == null ? null : params.get(key);
        if (value instanceof Number number) return number.intValue();
        if (value instanceof String string && !string.isBlank()) return Integer.parseInt(string);
        return defaultValue;
    }
}
