[package]
name = "chat-database-tool-client"
version = "0.0.1"
description = "智能数据库协作平台"
authors = ["you"]
edition = "2021"

[lib]
name = "chat_database_tool_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
