import type * as Monaco from 'monaco-editor'

export const LIGHT_MONACO_THEME = 'datatalk-sql-light'
export const DARK_MONACO_THEME = 'datatalk-sql-dark'

export function registerMonacoThemes(monaco: typeof Monaco) {
  monaco.editor.defineTheme(LIGHT_MONACO_THEME, {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'keyword', foreground: '27272a', fontStyle: 'bold' },
      { token: 'string', foreground: '52525b' },
      { token: 'number', foreground: '3f3f46' },
      { token: 'comment', foreground: 'a1a1aa', fontStyle: 'italic' },
      { token: 'identifier', foreground: '18181b' },
      { token: 'operator', foreground: '52525b' },
      { token: 'delimiter', foreground: '737373' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#171717',
      'editorGutter.background': '#fafafa',
      'editorLineNumber.foreground': '#a3a3a3',
      'editorLineNumber.activeForeground': '#171717',
      'editor.lineHighlightBackground': '#f5f5f5',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#e5e5e5',
      'editor.inactiveSelectionBackground': '#f5f5f5',
      'editorCursor.foreground': '#171717',
      'editorIndentGuide.background1': '#e5e5e5',
      'editorIndentGuide.activeBackground1': '#d4d4d4',
      'editorWidget.background': '#ffffff',
      'editorWidget.border': '#e5e5e5',
      'editorOverviewRuler.border': '#00000000',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.border': '#e5e5e5',
      'editorSuggestWidget.selectedBackground': '#f5f5f5',
      'list.hoverBackground': '#f5f5f5',
      'list.activeSelectionBackground': '#f5f5f5',
      'scrollbarSlider.background': '#d4d4d470',
      'scrollbarSlider.hoverBackground': '#a3a3a380',
      'menu.background': '#ffffff',
      'menu.foreground': '#171717',
      'menu.selectionBackground': '#f5f5f5',
      'menu.selectionForeground': '#171717',
      'menu.separatorBackground': '#e5e5e5',
      'menu.border': '#e5e5e5',
    },
  })
  monaco.editor.defineTheme(DARK_MONACO_THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'keyword', foreground: 'f4f4f5', fontStyle: 'bold' },
      { token: 'string', foreground: 'd4d4d8' },
      { token: 'number', foreground: 'e4e4e7' },
      { token: 'comment', foreground: '71717a', fontStyle: 'italic' },
      { token: 'identifier', foreground: 'fafafa' },
      { token: 'operator', foreground: 'a1a1aa' },
      { token: 'delimiter', foreground: 'a1a1aa' },
    ],
    colors: {
      'editor.background': '#171717',
      'editor.foreground': '#fafafa',
      'editorGutter.background': '#141414',
      'editorLineNumber.foreground': '#737373',
      'editorLineNumber.activeForeground': '#fafafa',
      'editor.lineHighlightBackground': '#262626',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#404040',
      'editor.inactiveSelectionBackground': '#262626',
      'editorCursor.foreground': '#fafafa',
      'editorIndentGuide.background1': '#404040',
      'editorIndentGuide.activeBackground1': '#525252',
      'editorWidget.background': '#1f1f1f',
      'editorWidget.border': '#404040',
      'editorOverviewRuler.border': '#00000000',
      'editorSuggestWidget.background': '#1f1f1f',
      'editorSuggestWidget.border': '#404040',
      'editorSuggestWidget.selectedBackground': '#262626',
      'list.hoverBackground': '#262626',
      'list.activeSelectionBackground': '#262626',
      'scrollbarSlider.background': '#40404070',
      'scrollbarSlider.hoverBackground': '#52525280',
      'menu.background': '#1f1f1f',
      'menu.foreground': '#fafafa',
      'menu.selectionBackground': '#262626',
      'menu.selectionForeground': '#fafafa',
      'menu.separatorBackground': '#404040',
      'menu.border': '#404040',
    },
  })
}
